-- CALIFORNIA STATE UNIVERSITY, SAN BERNARDINO
-- DEPARTMENT OF COMPUTER SCIENCE
-- Course: CSE572
-- STUDENT: JOSEPH CARMONA, JASMINE PENA
-- 
-- UNIVERSITY DATABASE PROJECT
-- TABLE AND COLUMN COMMENTS

COMMENT ON TABLE DEPARTMENT IS 'University department';
COMMENT ON COLUMN DEPARTMENT.DEPARTMENTNO IS 'Department identification number';
COMMENT ON COLUMN DEPARTMENT.MANAGERNO IS 'StaffNo of department manager';
COMMENT ON COLUMN DEPARTMENT.NAME IS 'Department name';
COMMENT ON COLUMN DEPARTMENT.PHONENO IS 'Phone number';
COMMENT ON COLUMN DEPARTMENT.FAXNO IS 'Fax number';
COMMENT ON COLUMN DEPARTMENT.LOCATION IS 'Department location';


COMMENT ON TABLE COURSE IS 'Department specific course';
COMMENT ON COLUMN COURSE.COURSENO IS 'Course identification number';
COMMENT ON COLUMN COURSE.DEPARTMENTNO IS 'Department identification number';
COMMENT ON COLUMN COURSE.MANAGERNO IS 'StaffNo of course manager';
COMMENT ON COLUMN COURSE.STUDENT_TOTAL IS 'Total number of students in a course';
COMMENT ON COLUMN COURSE.TITLE IS 'Course title';


COMMENT ON TABLE ACADEMIC_STAFF IS 'University academic staff member';
COMMENT ON COLUMN ACADEMIC_STAFF.STAFFNO IS 'Academic staff identification number';
COMMENT ON COLUMN ACADEMIC_STAFF.NETWORKID IS 'Unique network ID';
COMMENT ON COLUMN ACADEMIC_STAFF.DEPARTMENTNO IS 'Department identification number';
COMMENT ON COLUMN ACADEMIC_STAFF.FIRST_NAME IS 'Staff''s first name';
COMMENT ON COLUMN ACADEMIC_STAFF.LAST_NAME IS 'Staff''s last name';
COMMENT ON COLUMN ACADEMIC_STAFF.PHONEEXT IS 'Staff''s phone extension';
COMMENT ON COLUMN ACADEMIC_STAFF.OFFICENO IS 'Staff''s office number';
COMMENT ON COLUMN ACADEMIC_STAFF.SEX IS 'Staff''s sex (M or F)';
COMMENT ON COLUMN ACADEMIC_STAFF.SALARY IS 'Staff''s monthly salary';
COMMENT ON COLUMN ACADEMIC_STAFF.POST IS 'Position of academic staff member';
COMMENT ON COLUMN ACADEMIC_STAFF.QUALIFICATIONS IS 'Qualifications of academic staff member';
COMMENT ON COLUMN ACADEMIC_STAFF.STREET IS 'Staff''s street address';
COMMENT ON COLUMN ACADEMIC_STAFF.CITY IS 'Staff''s city address';
COMMENT ON COLUMN ACADEMIC_STAFF.STATE IS 'State code';
COMMENT ON COLUMN ACADEMIC_STAFF.ZIP IS 'ZIP code';
COMMENT ON COLUMN ACADEMIC_STAFF.START_DATE IS 'First day of employment';
COMMENT ON COLUMN ACADEMIC_STAFF.END_DATE IS 'Last day of employment';


COMMENT ON TABLE MODULE IS 'Course requirement';
COMMENT ON COLUMN MODULE.MODULENO IS 'Module identification number';
COMMENT ON COLUMN MODULE.MODULETITLE IS 'Title of a module';
COMMENT ON COLUMN MODULE.COURSENO IS 'Course identification number';
COMMENT ON COLUMN MODULE.COORDINATORNO IS 'StaffNo of module coordinator';
COMMENT ON COLUMN MODULE.START_DATE IS 'First day of a module';
COMMENT ON COLUMN MODULE.END_DATE IS 'Last day of a module';
COMMENT ON COLUMN MODULE.TEXTS IS 'Textbooks required by a module';
COMMENT ON COLUMN MODULE.ASSESSMENT_SCHEME IS 'Grading scheme used for a module';


COMMENT ON TABLE STUDENT IS 'University student';
COMMENT ON COLUMN STUDENT.MATRICULATIONNO IS 'Student identification number';
COMMENT ON COLUMN STUDENT.NETWORKID IS 'Unique network ID';
COMMENT ON COLUMN STUDENT.COURSENO IS 'Course identification number';
COMMENT ON COLUMN STUDENT.FIRST_NAME IS 'Student''s first name';
COMMENT ON COLUMN STUDENT.LAST_NAME IS 'Student''s last name';
COMMENT ON COLUMN STUDENT.STREET IS 'Student''s street address';
COMMENT ON COLUMN STUDENT.CITY IS 'Student''s city address';
COMMENT ON COLUMN STUDENT.STATE IS 'State code';
COMMENT ON COLUMN STUDENT.ZIP IS 'ZIP code';
COMMENT ON COLUMN STUDENT.DOB IS 'Student''s date of birth';
COMMENT ON COLUMN STUDENT.SEX IS 'Student''s sex (M or F)';
COMMENT ON COLUMN STUDENT.LOAN IS 'Student''s loan amount';
COMMENT ON COLUMN STUDENT.PERFORMANCE IS 'Student''s academic performance';


COMMENT ON TABLE NEXT_OF_KIN IS 'Student''s next-of-kin';
COMMENT ON COLUMN NEXT_OF_KIN.MATRICULATIONNO IS 'Student identification number';
COMMENT ON COLUMN NEXT_OF_KIN.FIRST_NAME IS 'Next-of-kin''s first name';
COMMENT ON COLUMN NEXT_OF_KIN.LAST_NAME IS 'Next-of-kin''s last name';
COMMENT ON COLUMN NEXT_OF_KIN.STREET IS 'Next-of-kin''s street address';
COMMENT ON COLUMN NEXT_OF_KIN.CITY IS 'Next-of-kin''s city address';
COMMENT ON COLUMN NEXT_OF_KIN.STATE IS 'State code';
COMMENT ON COLUMN NEXT_OF_KIN.ZIP IS 'ZIP code';
COMMENT ON COLUMN NEXT_OF_KIN.PHONENO IS 'Next-of-kin''s phone number';
COMMENT ON COLUMN NEXT_OF_KIN.RELATIONSHIP IS 'Next-of-kin''s relationship to the student';


COMMENT ON TABLE LECTURER_POSITION IS 'Academic staff member and the module they lecture';
COMMENT ON COLUMN LECTURER_POSITION.MODULENO IS 'Module identification number';
COMMENT ON COLUMN LECTURER_POSITION.STAFFNO IS 'Academic staff identification number';
COMMENT ON COLUMN LECTURER_POSITION.HOURS_WORKED IS 'Number of hours worked every week';


COMMENT ON TABLE SEAT IS 'Student and the module they are enrolled in';
COMMENT ON COLUMN SEAT.MODULENO IS 'Module identification number';
COMMENT ON COLUMN SEAT.MATRICULATIONNO IS 'Student identification number';

